global:
  scrape_interval: 15s # Intervalle global entre les scrapes

# Règles de scrape
scrape_configs:
  - job_name: "fastapi"
    metrics_path: "/metrics"
    static_configs:
      - targets: 
          - "fastapi_trad:8080" # Nom du conteneur Docker et port